spring:
  application:
    name: marketplace-api

  # Database Connection
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:marketplace_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secretpassword}
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate
  jpa:
    hibernate:
      # Use validate in production after migrations are introduced.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis Connection
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # Performance Tuning (Java 21 Virtual Threads)
  threads:
    virtual:
      enabled: true

# Swagger UI Config (http://localhost:8080/swagger-ui/index.html)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration-ms: 86400000

app:
  admin:
    username: ${ADMIN_USERNAME:system_admin}
    email: ${ADMIN_EMAIL:admin@marketplace.com}
    password: ${ADMIN_PASSWORD:Admin@1234}
    first-name: ${ADMIN_FIRST_NAME:System}
    last-name: ${ADMIN_LAST_NAME:Administrator}
